# SPDX-License-Identifier: AGPL-3.0-or-later
# cargo-deny configuration for ludoSpring
# Workspace path deps naturally lack version specs; wildcards = "warn" flags them
# without blocking CI. Registry deps are gated by allow-registry + unknown-registry.

[advisories]
unmaintained = "workspace"
yanked = "deny"

[licenses]
allow = [
    "AGPL-3.0-or-later",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "Zlib",
]

[bans]
multiple-versions = "warn"
wildcards = "warn"
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
